### ISSUE TITLE
Faire en sorte que le compteur de temps continue quand l'appli est en background

### ISSUE THREAD

**Issue by avianey** [NicolasJeannette/Quiz-Game#1]
Lorsque l'on joue on peut passer l'application en miniature et y revenir ensuite
Dans ce cas on peut réflechir tranquilement à la réponse sans que le compteur tourne
Il faut que quand on reviens sur l'appli on décompte les secondes passées en background
![Screenshot_20210302-150653_One UI Home](https://user-images.githubusercontent.com/1625652/109660501-3cfe1880-7b69-11eb-968a-7a09f518c70a.png)

**Comment by avianey** [comment]
voir au niveau du lifecycle applicatif : 
methodes onCreate, onResume onPause onSaveInstanceState de l'Activity

**Comment by NicolasJeannette** [comment]
Correction avec onStart() & onStop()
Commit : https://github.com/NicolasJeannette/Quiz-Game/commit/0f2be843b95a6751a737b07962473d201b696509
 https://github.com/NicolasJeannette/Quiz-Game/commit/10cbe5da96096d90a8b50fb8747fd01186d8bc71
